server:
  port: 8091
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver        #以前的com.mysql.jdbc.Driver不维护了，这个是最新的（功能：只是为了让后台窗口更加干净）
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
mybatis:
  mapper-locations: classpath:mybatis/*/*.xml        #配置mybatis的.xml文件路径o
logging:
  path: F:\\devProject\\project_logging\\Organ-Name      #此处只是举个例子，若是配置文件中存在file，path会失效
  config: classpath:logback-springs.xml
  level:
    # root日志以WARN级别输出
    root: debug                              #          trace<debug<info<warn<error      【级别越高日志打印越少】