server:
  port: 8091
spring:
  datasource:
    username: root
    url: jdbc:mysql://47.98.102.74:3306/sringboot?useUnicode=true&characterEncoding=utf8   #切记：阿里云服务器数据库名字与本地数据库名字取错了记住修改
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver        #以前的com.mysql.jdbc.Driver不维护了，这个是最新的（功能：只是为了让后台窗口更加干净）
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
  mail:
    host: smtp.163.com #邮箱服务器地址
    username: Wmz19960224@163.com #用户名
    password: 84471386zhi #开启POP3之后设置的客户端授权码e
    default-encoding: UTF-8
    # 超时时间（可选）
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  #redis config
  redis:
    database: 0   #数据库索引
    host: 192.168.214.1  #ip地址
    port: 6379     #端口号
    password: 123456   #密码
    timeout: 300     #连接超时时间
    jedis:
      pool:
        max-wait: -1    #连接池最大阻塞等待时间（负值表示没有限制）
        max-active: 8     #连接池最大连接数
        max-idle: 8    #连接池最大空闲时间
        min-idle: 0      #连接池最小连接时间
  #kafka config  (先注释掉不使用)
  #kafka:
    #bootstrap-servers: localhost:9092    #服务器地址
    #consumer:
      #group-id: mygroup
  #MongoDB config
  data:
    mongodb:
      host: 192.168.214.1
      #database: testdb
      #uri: mongodb://"":""@47.98.102.74:24000
      port: 27017
      username:
      password:
      database: testdbs
mybatis:
  mapper-locations: classpath:mybatis/*/*.xml        #配置mybatis的.xml文件路径o
logging:
  path: F:\\devProject\\project_logging\\Organ-Name      #此处只是举个例子，若是配置文件中存在file，path会失效
  config: classpath:logback-springs.xml
  level:
    # root日志以WARN级别输出
    root: info                              #          trace<debug<info<warn<error      【级别越高日志打印越少】
    org.springframework.data.mongodb.core: debug